### PR TITLE
Update README to describe converting finder schemas

### PR DESCRIPTION
**Pull request by heathd**
The process for adding a new specialist document format should also
include updating govuk-content-schemas appropriately to include the new
format.

### CODE REVIEW

**Comment by tommyp** [comment]
Can we add a section to the `README.md` about how to change a format with these changes? It should also probably specify that changing the `value` for any of the facet options is a bad idea because:

1. Links to pre-filtered Finders won't have that option selected
2. The old value won't be an option in the facet which means;
3. Any documents with the old `value` won't be filterable on that `value`
4. Any new documents published will have the new `value`, which will be different from the old one

The last 2 issues are fixable by republishing all the documents, but this isn't advisable as some of the specialist document formats have more than 10,000 documents.

Changing the label is fine though. :+1:

**Comment by heathd** [comment]
@tommyp I agree that some step-by-step instructions about modifying existing finders would be valuable but I think it's outside the scope of this pull request.

I'd be happy to sit with you and draft something (for a separate PR).

**Comment by danielroseman** [comment]
We also need to remove the section about govuk-content-models from this doc; there's no longer any need to do anything there.

**Comment by heathd** [comment]
Thanks @danielroseman, done

**Pull request merged**
