### PR TITLE
Fix broken links to finders in README

### PR DESCRIPTION
**Pull request by rgarner**
* And some titles, too

### CODE REVIEW

**Comment by issyl0** [comment]
Oh, hello! :star:

**Comment by rgarner** [comment]
Hai :small_orange_diamond:

**Comment by jamiecobbett** [comment]
:wave:

**Comment by elliotcm** [comment]
@rgarner were those URLs never live?  There's no redirects in place from the old ones.

**Comment by elliotcm** [comment]
Github won't even let me do a manual merge while that status check is pending :/

**Comment by rgarner** [comment]
@elliotcm don't think so - same sort of typos in them, looks like they were transcribed by hand and never clicked*

*speculation

**Pull request merged**
