### PR TITLE
Migrate formats for vehicle recalls and faults alerts

### PR DESCRIPTION
**Pull request by Rosa-Fox**
https://trello.com/c/zvp2e2SG/538-vehicle-faults

### CODE REVIEW

**Comment by Rosa-Fox** [comment]
https://trello.com/c/zvp2e2SG/538-vehicle-faults

**Comment by jamiecobbett** [comment]
I think it would be a good idea to start including screen shots on these PRs. Here's one for this:
screen shot 2016-02-15 at 13 50 09

**Comment by tommyp** [comment]
@jamiecobbett The markup for these is the same. The frontend isn't changing with these PRs.

**Comment by jamiecobbett** [comment]
@tommyp that's not strictly true - the "Body" textarea is far smaller on this branch than master - 2 rows instead of 20.

**Comment by tommyp** [comment]
You're right. I copied the CSS over so I'm guessing this comes from https://github.com/elliotcm/generic_form_builder.

**Comment by boffbowsh** [comment]
Same comments here as on https://github.com/alphagov/specialist-publisher/pull/654

**Comment by gpeng** [comment]
@boffbowsh Fixed in 4a18745

**Comment by gpeng** [comment]
@jamiecobbett We'll address the 'row' issue in another PR.

**Comment by fofr** [comment]
From the screenshot it looks like these fields aren't using the correct Bootstrap form classes. The spacing is a bit too bunched together.

**Pull request merged**
