### PR TITLE
Update tribunal_decision_judges for UTAAC finder

### PR DESCRIPTION
**Pull request by lgarvey**
The list of judges has changed for the UTAAC finder

### CODE REVIEW

**Comment by tijmenb** [comment]
There are 4 decisions tagged to the judge that has been removed (`bruner-k`):

``` ruby
content_items = ContentItem.where(document_type: "utaac_decision").select { |item|
  item['details']['metadata']['tribunal_decision_judges'].include?("bruner-k")
}

puts content_items.map { |item| "https://specialist-publisher.publishing.service.gov.uk/utaac-decisions/" + item['content_id'] }
```

Items:

https://specialist-publisher.publishing.service.gov.uk/utaac-decisions/b682a0dd-c50b-49d9-abf3-076a42929a63
https://specialist-publisher.publishing.service.gov.uk/utaac-decisions/b2b0bd35-58d2-420d-b22a-ab19cf8bd1bc
https://specialist-publisher.publishing.service.gov.uk/utaac-decisions/a2ff8699-5f0a-45c7-b145-9a6410f28608
https://specialist-publisher.publishing.service.gov.uk/utaac-decisions/49997dde-256e-414c-966b-a54d734e6068

These will have to be fixed manually.

**Comment by lgarvey** [comment]
Bruner-k was actually a spelling mistake.  The correct name is Brunner-k,
which has been added to the PR.  So presumably those items will need to
have the correct category added to them?

**Comment by tijmenb** [comment]
@lgarvey has confirmed via Tom WM that these are the correct changes to make. Merging!

**Comment by tijmenb** [comment]
This has been deployed. I've fixed re-assigned the existing documents above to the renamed judge.

**Pull request merged**
