### PR TITLE
Update email alert options for the Employment Tribunal Decisions finder

### PR DESCRIPTION
**Pull request by lgarvey**
A change to the email categories for the MOJ ET finder

### CODE REVIEW

**Comment by tijmenb** [comment]
This PR has some of the same changes in utaac_decisions.json as https://github.com/alphagov/specialist-publisher/pull/925, can you remove those?

**Comment by tijmenb** [comment]
For some context, this PR should change the options for the email alerts for the finder.

I've published the finder on integration using the rake task:

https://deploy.integration.publishing.service.gov.uk/job/run-rake-task/459/console

Which will make it visible in integration:

https://www-origin.integration.publishing.service.gov.uk/employment-tribunal-decisions

It currently shows this when you click the "Subscribe to email alerts" button:

screen shot 2016-10-24 at 19 38 30

I think the way that this is code reviewed is by checking that the `key` in each email alert choice corresponds to a valid `tribunal_decision_categories` (as configured by the [email_filter_by option](https://github.com/alphagov/specialist-publisher/blob/64fda6bb6b20af650924b6bb7a8ed3398b0a91f5/lib/documents/schemas/employment_tribunal_decisions.json#L23)).

I will check tomorrow if this is something we can do automatically. Otherwise the danger exists that users subscribe to email alerts that will never be sent out.

**Comment by tijmenb** [comment]
This now fails correctly because one of the categories doesn't exist yet. Once https://github.com/alphagov/specialist-publisher/pull/924 is merged this will be green and can get merged.

**Comment by tijmenb** [comment]
I've squashed this commit and force-pushed.

The tests don't pass because `employment-agencies-act-1973-obsolete-topic` is not a valid thing anymore (it was removed in https://github.com/alphagov/specialist-publisher/pull/924).

There are a bunch of other "obsolete" topics still, do we want to remove them?

**Comment by lgarvey** [comment]
All the -obsolete-topic topics have been removed from the ET finder.  That
convention may have been used elsewhere in others finders, so if possible
only tests relating to the ET finder should be amended.

**Comment by tijmenb** [comment]
This should be rebased after https://github.com/alphagov/specialist-publisher/pull/932 is merged.

**Comment by tijmenb** [comment]
Rebased & all passing. Merging.

**Pull request merged**
