### PR TITLE
Test length of subscription list names

### PR DESCRIPTION
**Pull request by rubenarakelyan**
This commit amend the test for the length of subscription list names to take into account the change of approach in how the names are generated. It now checks to make sure either the prefix (where only the prefix is used) or the plural prefix with all topics appended is a maximum of 255 characters long. Any finders that are not live are excluded from this test to allow for pre-production testing.

Trello: https://trello.com/c/KTHRa4a0/422-fix-email-alert-api-errors-when-the-email-alert-short-name-is-longer-than-255-characters

### CODE REVIEW

**Comment by tijmenb** [comment]
This fails for CMA cases, what can we do about that?

https://ci.integration.publishing.service.gov.uk/job/specialist-publisher/job/test-length-of-subscription-list-names/2/console

**Comment by rubenarakelyan** [comment]
Yup that's expected. Once https://github.com/alphagov/specialist-publisher/pull/990 is merged then this will go green.

**Comment by tijmenb** [comment]
Reviewing in the wrong order :) That's merged now, can you rebase?

**Comment by rubenarakelyan** [comment]
Ready

**Pull request merged**
