### PR TITLE
Update assets domain

### PR DESCRIPTION
**Pull request by alexmuller**
This has changed in production.

### CODE REVIEW

**Comment by benilovj** [comment]
@alexmuller looks like there is a lint error on your change...

**Comment by alexmuller** [comment]
Thanks, should be fixed.

**Comment by alexmuller** [comment]
Hm, I don't understand the test failure I'm afraid:

```
  1) Republishing documents for drafts should add job to worker queue when republishing all documents
     Failure/Error: expect(RepublishDocumentWorker.jobs.size).to eq(2)
```

**Comment by benilovj** [comment]
The breakage isn't related to your change – it's caused by a flaky test. I've [opened a PR](https://github.com/alphagov/specialist-publisher/pull/720) which should hopefully harden the spec. Once that's merged, we can rebase your branch...

**Pull request merged**
