### PR TITLE
Revert "Revert "Add regions to business finance support scheme""

### PR DESCRIPTION
**Pull request by elliotcm**
Restores alphagov/specialist-publisher#1235

https://trello.com/c/yUWfjwSN/514-deploy-regional-location-facet-to-finance-and-support-for-your-business-finder

### CODE REVIEW

**Review by steventux — APPROVED** [review]

**Review by thomasleese — APPROVED** [review]

**Comment by rubenarakelyan** [comment]
Making this DNM until we get the go ahead.

**Comment by stevenjmesser** [comment]
https://trello.com/c/yUWfjwSN/514-deploy-regional-location-facet-to-finance-and-support-for-your-business-finder

**Comment by steventux** [comment]
@elliotcm @thomasleese this needs a re-up as I've had to push a commit to fix a test.

**Comment by elliotcm** [comment]
@steventux Looks like the end to end tests are failing.  Do they just need re-running?

**Comment by elliotcm** [comment]
That said, it looks like it's still accepting the old review.

**Pull request merged**
