### PR TITLE
No longer sends alert to email-alert-api on publish for drug_safety_u…

### PR DESCRIPTION
**Pull request by Rosa-Fox**
…pdate format

### CODE REVIEW

**Comment by Rosa-Fox** [comment]
[Trello card](https://trello.com/c/ploRXLJV/16-email-alerts)

**Comment by gpeng** [comment]
Hi Rosa... Could you add some context to the PR and the commit message?

**Comment by Rosa-Fox** [comment]
Hi @gpeng,

This requirement is listed as a feature on the previous version of specialist-publisher [here.](https://github.com/alphagov/specialist-publisher/blob/master/features/publishing-a-drug-safety-update.feature#L30-L60).

According to [this commit:](https://github.com/alphagov/specialist-publisher/commit/d3c7922380f17e4f6d81e538dc7082c5215363d6)

“The Drug Safety Update is a monthly newsletter sent by the MHRA with custom
content (the full content of the document body). Therefore we're going to allow
the MHRA to send this out manually rather than alerting the user each time a
new one is published.”.

Drug Safety Updates didn’t seem to be sent out from the previous version of specialist-publisher so is possibly done through Gov Delivery.

This PR ensures that Drug Safety Updates are published but email-alerts are not triggered automatically as they are with the other formats.

**Comment by benilovj** [comment]
Rosa, the info in [your comment](https://github.com/alphagov/specialist-publisher/pull/691#issuecomment-204326952) is really useful. To preserve it, could you add it to the commit description, as that would help future developers who go spelunking in this codebase?

Also, could you shorten the commit summary to be less than 50 characters to be in line with our [style guide](https://github.com/alphagov/styleguides/blob/master/git.md#structure)?

**Comment by Rosa-Fox** [comment]
Thanks @benilovj, I have made the changes.

**Comment by sihugh** [comment]
:+1:

**Pull request merged**
